image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - rm -rf node_modules
    - rm -f package-lock.json
    - npm install
    - npm run build
    - rm -rf dev
    - rm -rf src
    - npm prune --omit=dev
    - ls -alh
    - touch .npmrc
    - echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/">.npmrc
    - echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc
    - cat .npmrc
    - npm publish
  only:
    - main