name: CI

on:
  workflow_dispatch:
    branches:
      - alpha

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: pnpm install
      - run: pnpm run ci
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
